### ISSUE TITLE
[TODO] TODO list (updated)

### ISSUE THREAD

**Issue by josh-hsu** [josh-hsu/Josh-Tool#1]
**joshtool.cpp**
- [x] Need to change SevenKnight keyword to GameModule (or just game). The job map can be configured at Android Application side.

**CoreService.cpp**
- [x] This class should not be named CoreService because it's not providing any core component related functions. It only provides setting connection and user notifications. I haven't come through the name 

**APP**
- [ ]  I will upload Android Application source code as soon as I removed my company's name in package. (The reason is I was too lazy to rename it...)

**SevenKnight.cpp**
- [ ] Make normal battle configurable with battle count
- [ ] Capture screendump for Aragon screen and player level up screen.
- [ ] Make delay time configurable for hero changing and battle.

**Comment by josh-hsu** [comment]
SevenKnight is no longer supported.
